// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ilqhnnwucuvsnrstlfbs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlscWhubnd1Y3V2c25yc3RsZmJzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwMTc1NjIsImV4cCI6MjA3MjU5MzU2Mn0.hkCgvzUQgM_ViejAheZCRg_GKhqO6Gj41kcdu2W92bo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});